title: Ching Fhen's Portfolio
logo: /assets/images/logo0.jpg
description: Experienced Data Scientist with half a decade of experience. Capable of delivering full stack AI Applications.
show_downloads: false
# google_analytics:
# theme: jekyll-theme-minimal
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme